
{
 :name "collect-barcode-stats",
 :path "",
 :func (fn [eid & data]
         (if (pg/eoi? eid)
           (pg/done)
           (do
             (infof "Collect barcode stats from fastqs for Exp %s" eid)
             [eid (htrs/collect-barcode-stats eid)])))
 ;; instructional data used in /help
 :description "Collect barcode statistic maps for fastq.gz files generated by experiment EID"
}
