
{
 :name "write-bcmaps",
 :path "",
 :func (fn [eid-bcmap-vec & data]
         (if (vector? eid-bcmap-vec)
           (let [[eid bcmaps] eid-bcmap-vec]
             (infof "Write barcode stats for %s" eid)
             (htrs/write-bcmaps eid bcmaps)
             eid)
           (pg/done)))
 ;; instructional data used in /help
 :description "Write out the barcode statistic maps for experiment with id EID and as generated by collect-barcode-stats",
}
